# Generated by Django 3.0.4 on 2020-03-23 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('distance', models.FloatField(verbose_name='Дистанция в км')),
                ('time', models.FloatField(verbose_name='Время бега в минутах')),
                ('date', models.DateField(default=datetime.datetime(2020, 3, 23, 12, 0, 39, 276551, tzinfo=utc), verbose_name='Дата бега')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
