# Generated by Django 3.0.4 on 2020-03-24 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20200323_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дистанция в км'),
        ),
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Время бега в минутах'),
        ),
    ]
