# Generated by Django 3.0.4 on 2020-03-22 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, error_messages={'unique': 'У вас уже есть тренировка в этот день!'}, unique=True, verbose_name='Дата тренировки'),
        ),
    ]
