# Generated by Django 3.0.4 on 2020-03-22 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200322_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата тренировки'),
        ),
    ]
