# Generated by Django 3.0.4 on 2020-03-26 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200322_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование упражнения')),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Подходы')),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Повторения')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='workouts.Exercise'),
        ),
    ]
