# Generated by Django 3.0.4 on 2020-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0004_auto_20200326_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='exercises.Exercise'),
        ),
    ]
