# Generated by Django 3.0.4 on 2020-03-24 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imts', '0002_auto_20200324_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imt',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(300)], verbose_name='Рост в см'),
        ),
        migrations.AlterField(
            model_name='imt',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Вес в кг'),
        ),
    ]
