# Generated by Django 3.0.4 on 2020-03-24 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imts', '0004_auto_20200324_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imt',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рост в см'),
        ),
        migrations.AlterField(
            model_name='imt',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес в кг'),
        ),
    ]
